services:
  mongo:
    image: mongo:7
    container_name: chatbot-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatbot
      MONGO_INITDB_ROOT_PASSWORD: chatbot_password
      MONGO_INITDB_DATABASE: chatbot
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:16
    container_name: nest-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot_password666
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data:
