export const AiProviderResponseCode = {
  SETTING_UPDATED: 'AI_PROVIDER_SETTING_UPDATED',
  SETTING_CREATED: 'AI_PROVIDER_SETTING_CREATED',
  SETTING_FOUND: 'AI_PROVIDER_SETTING_FOUND',

  SETTING_NOT_FOUND: 'AI_PROVIDER_SETTING_NOT_FOUND',
  INVALID_SCOPE: 'AI_PROVIDER_INVALID_SCOPE',
  PROVIDER_NOT_SUPPORTED: 'AI_PROVIDER_NOT_SUPPORTED',
  MODEL_NOT_SUPPORTED: 'AI_PROVIDER_MODEL_NOT_SUPPORTED',
  UPDATE_FAILED: 'AI_PROVIDER_SETTING_UPDATE_FAILED',
} as const;

export type AiProviderResponseCode =
  (typeof AiProviderResponseCode)[keyof typeof AiProviderResponseCode];